local event = require("debeat.event")

function init(self)
	msg.post("#", "hide")
	self.t = 0
end

function update(self, dt)
	if self.t < 0 then
		msg.post("#", "hide")
	else
		self.t = self.t - dt
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("hide") then
		msg.post("#", "disable")
		event.trigger(hash("hide_no_drop_room"))
	elseif message_id == hash("show") then
		self.t = 1
		msg.post("#", "enable")
		event.trigger(hash("show_no_drop_room"))
	end
end